### ISSUE TITLE
When compiling or initializing pytypes SSLCertVerificationError is thrown

### ISSUE THREAD

**Issue by baileyspraggins** [Ackee-Blockchain/wake#295]
Hi. First time using Wake. Super excited to try it out. When trying to integrate it into on of my current repos I am unable to compile or set up `pytypes`. I have tried this on a fresh project as well using the installation instructions provided within the docs. The following commands I have tried and received this error for are `wake init pytypes -w` and `wake compile`.

Error message
`SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1002)`

**Comment by michprev** [comment]
Hello @baileyspraggins, this is caused by Wake trying to download a compiler binary. There is a known Python post-installation issue/required step on macOS. Can you please try running the command in this answer https://github.com/Ackee-Blockchain/tools-for-solidity-vscode/issues/44#issuecomment-1441631192?
